[project]
name = "cl-2026-2-lab"
version = "0.0.4"
description = "Repositorio para prácticas de laboratorio del curso de Lingüística Computacional 2026-2"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-ruff>=0.3.1",
    "jupyterlab>=4.5.3",
    "jupytext>=1.19.1",
]
